language: python
python:
    - 2.7

env:
  - MPI=openmpi

virtualenv:
  system_site_packages: true

branches:
  only:
    - master

before_install:
  # Use miniconda and conda packages to speed up dependency setup (principally 
  # borrowed from https://gist.github.com/dan-blanchard/7045057
  # and https://github.com/Jorge-C/ordination/blob/master/.travis.yml
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran python-qt4
  - test $MPI == openmpi && MPIPACKAGES='openmpi-bin openmpi-dev'          || true
  - sudo apt-get install -qq $MPIPACKAGES
  - wget http://repo.continuum.io/miniconda/Miniconda-2.2.2-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=$HOME/anaconda/bin:$PATH
  # Update conda itself
  - conda update --yes conda
  # Additional channel for pyqt4
  - conda config --add channels asmeurer
  # matplotlib needs a DISPLAY
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"


install:
  - conda create --yes -n pelenv python=$TRAVIS_PYTHON_VERSION nose pip cython numpy scipy matplotlib qt pyqt
  - source activate pelenv
  - pip install --use-mirrors networkx sqlalchemy hungarian pyro4 brewer2mpl pyopengl mpi4py
  - git clone https://github.com/pele-python/pele.git
  - cd pele
  - python setup.py build --fcompiler=gfortran
  - python setup.py install
  - cd ..
  - python setup.py build --fcompiler=gfortran
  - python setup.py install

script:
  # avoid running in the checkout directory so nose finds built modules..
  - cd $HOME
  - nosetests pele
  # do the c++ tests
  #- $cpp_test_dir/build/test_main
